import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import User from "@/components/User";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex justify-center relative">
        <Navbar />
        <main>{children}</main>
        <User/>
      </body>
    </html>
  );
}
